name: Build
on:
  push:
    branches:
      - master
    tags:
      - *
env:
  VERSION: 0.3.0
  YUM_REGISTRY: https://binary.picodata.io/repository/yum
jobs:
  build:
    name: Build genin binary
    runs-on: [self-hosted, genin]
    container:
      image: docker.binary.picodata.io/rust-builder-nightly:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version from tag
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Run make build
        run: make build
      - name: Run pack binaries
        run: make pack
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.zip
          path: target/package/*

  centos7:
    name: Build centos 7 rpm
    needs: build
    runs-on: [self-hosted, genin]
    container:
      image: docker.binary.picodata.io/centos:centos7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download builded binary
        uses: actions/download-artifact@v3
        with:
          name: artifacts.zip
          path: .
      - run: yum install -y rpm-build rpm-devel rpmdevtools make
      - run: sed -ie "s/\${VERSION}/${VERSION}/g" build/el7/genin.x86_64.spec
      - run: rpmdev-setuptree
      - run: rpmbuild -bb build/el7/genin.x86_64.spec
      - run: mv ~/rpmbuild/RPMS/x86_64/genin-${VERSION}-1.el7.x86_64.rpm genin-${VERSION}-1.el7.x86_64.rpm
      - run: 'curl -v -f -H "Authorization: Basic ${{ secrets.YUM_AUTH_RW }}" --upload-file genin-${VERSION}-1.el7.x86_64.rpm ${YUM_REGISTRY}/el/7/x86_64/os/genin-${VERSION}-1.el7.x86_64.rpm'

  centos8:
    name: Build centos 8 prm
    needs: build
    runs-on: [self-hosted, genin]
    container:
      image: docker.binary.picodata.io/rockylinux:8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download builded binary
        uses: actions/download-artifact@v3
        with:
          name: artifacts.zip
          path: .
      - run: yum install -y rpm-build rpm-devel rpmdevtools make
      - run: sed -ie "s/\${VERSION}/${VERSION}/g" build/el8/genin.x86_64.spec
      - run: rpmdev-setuptree
      - run: rpmbuild -bb build/el8/genin.x86_64.spec
      - run: mv ~/rpmbuild/RPMS/x86_64/genin-${VERSION}-1.el8.x86_64.rpm genin-${VERSION}-1.el8.x86_64.rpm
      - run: 'curl -v -f -H "Authorization: Basic ${{ secrets.YUM_AUTH_RW }}" --upload-file genin-${VERSION}-1.el8.x86_64.rpm ${YUM_REGISTRY}/el/7/x86_64/os/genin-${VERSION}-1.el8.x86_64.rpm'
