name: IntegrationTest
on:
  push:
    branches:
      - master
      - pull_request
jobs:
  test:
    name: Run integrations tests
    runs-on: [self-hosted, genin]
    steps:
      - name: dummy
        run: echo "hello"
