name: UnitTest
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    name: Cargo run tests
    runs-on: [self-hosted, genin]
    container:
      image: docker.binary.picodata.io/rust-builder-nightly:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tests
        run: cargo +nightly test
